# Generated by Django 5.2.11 on 2026-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fiction', 'Badiiy'), ('non_fiction', 'Publitsistika'), ('science', 'Ilmiy'), ('history', 'Tarix'), ('biography', 'Biografiya'), ('fantasy', 'Fantastika'), ('mystery', 'Detektiv'), ('romance', 'Romantik'), ('thriller', 'Triller'), ('other', 'Boshqa')], default='other', max_length=50),
        ),
    ]
